---
- hosts: webservers 
  become: true
  remote_user: true
  tasks:
    - name: Install apache2
      apt:
        name: apache2
        state: latest
    - name: run apache2
      service:
        name: apache2
        state: started
    - name: create content
      copy:
        content: "Congrats on installing apache2"
        dest: /var/www/html/index.html
...
